#!/usr/bin/env ruby
require 'erb'
require 'nokogiri'
dir = File.dirname(__FILE__)
require "#{dir}/common.rb"
require "#{dir}/svd_parser.rb"

if ARGV[0].nil?
  print "Usage: #{__FILE__} [chip-name]\n"
  exit 1
end

chip = ARGV[0]
is_test = chip == 'test'
filename = "svd/stm32f#{chip[0..2]}.svd"
filename = 'data/test.svd' if is_test
@doc = File.open(filename) { |f| Nokogiri::XML(f) }
device = Device.new(@doc)

def generate(device)
  tmpl = <<~EOF
    pub const registers = struct {
        <%- for p in device.peripherals -%>
        /// <%= p.desc %>
        pub const <%= p.name %> = struct {
            pub const base_address = <%= p.base_address.to_hex %>;
            <%- for r in p.registers %>
            /// address: <%= r.address(p.base_address).to_hex %>
            /// <%= r.desc %>
            <%- case r.type -%>
            <%- when :int -%>
            pub const <%= r.name %> = @intToPtr(*volatile u<%= r.size %>, base_address + <%= r.address_offset.to_hex %>);
            <%- when :mmio_int -%>
            pub const <%= r.name %> = @intToPtr(*volatile MmioInt(<%= r.size %>, u<%= r.bit_width %>), base_address + <%= r.address_offset.to_hex %>);
            <%- else -%>
            pub const <%= r.name %> = @intToPtr(*volatile Mmio(<%= r.size %>, packed struct {
                <%- for f in r.fields -%>
                <%= f.name %>: u<%= f.bit_width %>,<%- if f.desc -%> // <%= f.desc %> <%- end %>
                <%- end -%>
            }), base_address + <%= r.address_offset.to_hex %>);
            <%- end -%>
            <%- end -%>
        };
        <%- end -%>
    };

  EOF
  puts ERB.new(tmpl, trim_mode: '-').result(binding)
end

puts "// this file was generated by cgen/#{File.basename(__FILE__)}"
generate(device)
puts File.read('data/registers_footer.zig') unless is_test
